---
kind: pipeline
name: Test

steps:
    - name: Python 3.5
      image: python:3.5
      commands:
          - python setup.py install
          - python setup.py test
    - name: Python 3.6
      image: python:3.6
      commands:
          - python setup.py install
          - python setup.py test
    - name: Python 3.7
      image: python:3.7
      commands:
          - python setup.py install
          - python setup.py test
